name: build_psmodule

on:
#  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]

    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        id: setup_dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install PowerShell
        id: install_powershell
        uses: PSModule/install-powershell@v1
        with:
          Version: 7.5.4

      - name: Install prerequisite PS modules
        id: install_ps_modules
        if: ${{ steps.install_powershell.outcome == 'success' }}
        shell: pwsh
        run: |
          Install-Module -Name "PowerShellGet" -Force -Confirm:$false -Scope CurrentUser
          Install-Module -Name "PlatyPS" -Force -Confirm:$false -Scope CurrentUser

      - name: Install Paket
        id: install_paket
        if : ${{ steps.setup_dotnet.outcome == 'success' && steps.install_powershell.outcome == 'success' }}
        run: |
          dotnet tool install --global Paket
          dotnet tool restore

      - name: Restore project dependencies
        id: restore_dependencies
        if: ${{ steps.install_paket.outcome == 'success' }}
        run: |
          dotnet paket install

      - name: Build PSPhlebotomist PowerShell Module
        id: build_module
        if: ${{ steps.restore_dependencies.outcome == 'success' }}
        run: dotnet build --configuration Release PSPhlebotomist.sln

      - name: Dotnet publish
        id: dotnet_publish
        if: ${{ steps.build_module.outcome == 'success' }}
        run: dotnet publish --configuration Release
      
      - name: Publish PS Module
        id: publish_ps_module
        if: ${{ steps.dotnet_publish.outcome == 'success' }}
        shell: pwsh
        run: |
          $ProjectName = "PSPhlebotomist"
          $IconFilename = "PSPhlebotomist_256x256.png"
          $PSGalleryIconFilename = "PSPhlebotomist_85x85.png"
          $FilesToCopy = @(
              "README.md",
              "LICENSE",
              "VERSION",
              "$(Join-Path -Path "${ProjectName}" -ChildPath "Properties" -AdditionalChildPath @(
                "res",
                "${IconFilename}"
              ))",
              "$(Join-Path -Path "${ProjectName}" -ChildPath "Properties" -AdditionalChildPath @(
                "res",
                "${PSGalleryIconFilename}"
              ))"
          )
          $PublishPath = Join-Path -Path "${{ github.workspace }}" -ChildPath "${ProjectName}" -AdditionalChildPath @(
            "bin",
            "Release",
            "netstandard2.0"
          )
          Set-Location "${PublishPath}"
          Rename-Item -Path ".\publish" -NewName "${ProjectName}"

          foreach ($File in $FilesToCopy)
          {
              Copy-Item -Path "$(Join-Path -Path "${{ github.workspace}}" -ChildPath "${File}")" -Destination ".\${ProjectName}\" -Force -Verbose
          }
          Publish-Module -Path ".\${ProjectName}" -NuGetApiKey ${{ secrets.GALLERY_API_KEY }} -Force -Confirm:$false -Verbose
